# Generated by Django 5.2 on 2025-05-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
