# Generated by Django 5.2 on 2025-04-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_board_end_date_board_location_board_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#CCCCCC', max_length=7),
        ),
    ]
